// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOUryXPEeW3iqVX7HKOUIvOyVP1CVNzR4',
    appId: '1:467477031108:web:eda0c29eefb8cdac954191',
    messagingSenderId: '467477031108',
    projectId: 'flutter-f965c',
    authDomain: 'flutter-f965c.firebaseapp.com',
    storageBucket: 'flutter-f965c.firebasestorage.app',
    measurementId: 'G-Z7KR5VVF1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzC8-W6jO4U_FcLSwOjVvncfAkBkKOeKM',
    appId: '1:467477031108:android:93eb3a25482f615f954191',
    messagingSenderId: '467477031108',
    projectId: 'flutter-f965c',
    storageBucket: 'flutter-f965c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfF-bxMxB0PfQMYlr9X91G38iBMAWWFEc',
    appId: '1:467477031108:ios:8516b1c536616dd4954191',
    messagingSenderId: '467477031108',
    projectId: 'flutter-f965c',
    storageBucket: 'flutter-f965c.firebasestorage.app',
    iosBundleId: 'com.example.helloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfF-bxMxB0PfQMYlr9X91G38iBMAWWFEc',
    appId: '1:467477031108:ios:8516b1c536616dd4954191',
    messagingSenderId: '467477031108',
    projectId: 'flutter-f965c',
    storageBucket: 'flutter-f965c.firebasestorage.app',
    iosBundleId: 'com.example.helloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOUryXPEeW3iqVX7HKOUIvOyVP1CVNzR4',
    appId: '1:467477031108:web:4ae92a9ba82f7ee2954191',
    messagingSenderId: '467477031108',
    projectId: 'flutter-f965c',
    authDomain: 'flutter-f965c.firebaseapp.com',
    storageBucket: 'flutter-f965c.firebasestorage.app',
    measurementId: 'G-YVBBX1LRMT',
  );
}
